# Generated by Django 4.1.7 on 2023-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
