from django import forms

class serverForm(forms.Form):
    nameServer = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Ingrese el nombre del servidor'}))
    osServer = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Ingrese el sistema operativo del servidor'}))
    ipServer = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Introduzca la ip del servidor'}))
    path = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Introduzca el path donde se ubican los backups'}))
    adminUser = forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Ingrese el usuario admin'}))
    adminPassword= forms.CharField(max_length=255,widget=forms.TextInput(attrs={'class': 'mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 text-gray-900','placeholder': 'Ingrese el password del usuario admin'}))
    